### ISSUE TITLE
trying to get things set up

### ISSUE THREAD

**Issue by jshulters** [necrosoftgames/differently#3]
Apologies for probably overlooking something very simple, but I can't for the life of me get my content to display. I've placed everything is a  "presskit" subfolder under my domain, edited and uploaded my index.md file, and created a banner image so far. The content has been upload via FTP, but when I browse to the site (in different browsers, different machines, private tabs, etc), it still just shows the original placeholder content. I can delete the folder and a page not found appears, so I know it's looking in the right place. Do you know what I'm missing? Thanks so much!

http://blackstrawgames.com/presskit

**Comment by jshulters** [comment]
Sorry. Maybe an issue with my web host. After waiting a few hours, things are showing correctly now.

**Comment by unknowndevice** [comment]
Glad it's working!
