### ISSUE TITLE
Unable to load index.html

### ISSUE THREAD

**Issue by DeeCeptor** [necrosoftgames/differently#4]
Hi. When using Chrome or Firefox, neither of the index.html files load. Here is the error from the Chrome browser window:
XMLHttpRequest cannot load file:///C:/Programming/differently_presskit/index.md. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.send @ jquery.min.js:4
flatdoc.js:6 [Flatdoc] fetching Markdown data failed. Object(anonymous function) @ flatdoc.js:6

**Comment by unknowndevice** [comment]
Oh hey. Sorry I only saw this now. If you're running it locally then you're need server it with a server otherwise the javascript won't load. If you've installed python you can cd to the directory and start a server.

```
python -m SimpleHTTPServer
```
